### ISSUE TITLE
Segmentation fault during installation

### ISSUE THREAD

**Issue by rwanwork** [wzthu/esATAC#123]
Thank you for providing this package!

I was trying to install it into R 3.4.1 via Anaconda.  I finally got all the dependencies working but now, it's having a problem with this package specifically.  This is what I see:

```
installing to ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Segmentation fault (core dumped)
ERROR: loading failed

```

Do you have any advice on what I should do?  Perhaps I should use another version of R?

**Comment by wzthu** [comment]
We did not test the package for R in Anaconda. But the problem probably caused by the dependency package rJava loading. Please check if you can load rJava successfully first;
```
library(rJava)
.jinit()
```

**Comment by rwanwork** [comment]
Thanks for your reply!  I just tried the above two lines and there was no problem.

I'm not too familiar with software installation using Bioconductor.  Is there a way I can show you a log file indicating the part that is causing the segmentation fault?

Which versions of R did you test your software under?  I realize that a minor difference in R version may be nothing, but it can affect some library that might have changed significantly.

**Comment by wzthu** [comment]
If you want to use newest version Bioconductor 3.7(<http://bioconductor.org/packages/3.7/bioc/html/esATAC.html>)), you need to install (>=R3.5.) You are now using R3.4.1 so the Bioconductor version is 3.6(<http://bioconductor.org/packages/3.6/bioc/html/esATAC.html>). The package is built and checked everyday on Bioconductor build servers with R3.5.0 now.

Maybe there is not any log files during installation. You have to load dependency package like rJava respectively to check which dependency package can not be loaded:

Rcpp (>= 0.12.11), methods, knitr, Rbowtie2, rtracklayer, ggplot2, Biostrings, ChIPseeker, clusterProfiler, igraph, rJava, DiagrammeR, magrittr, digest, BSgenome, AnnotationDbi, GenomicFeatures, R.utils, GenomeInfoDb, BiocGenerics, S4Vectors, IRanges, rmarkdown, tools, VennDiagram, grid, JASPAR2016, TFBSTools, grDevices, graphics, stats, utils, parallel, corrplot, BiocInstaller

**Comment by rwanwork** [comment]
I see.  Prior to the segmentation fault, there were no other errors.  All dependencies appeared to load fine.  That segmentation fault is the first error that occurs. 

With a newer version of R, I actually had problems with some of the dependencies...so that's why I'm using 3.4.1 on purpose.  But let me try 3.5 a bit harder...hopefully I can figure it out.  Thanks a lot for your help!

**Comment by rwanwork** [comment]
Just a quick update -- it turns out that R 3.5.0 is not yet available for Ubuntu (the OS I use) and Anaconda.  Other dependencies within Anaconda prevent me from using 3.4.3 (for some reason, downloading these dependencies with Bioconductor gave me various errors).

Anyway, I downloaded the R 3.5.0 source and compiled it and then installed esATAC according to the instructions and this all went fine!  Thanks a lot for your help!
