### ISSUE TITLE
Error at peak calling stage

### ISSUE THREAD

**Issue by m4gold** [wzthu/esATAC#126]
Hi,
When running the pipelines (atacPipe, atacPipe2 etc.), the run successfully completes at times while at other times it stops at the peak calling stage with the following error:
F-Seq Version 1.85
Error in strsplit(filename[i], split = "\\.")[[1]] : 
  subscript out of bounds
Execution halted

Do you know what might be causing this error or how I can solve it?
Thank in advance!

**Comment by wzthu** [comment]
Please see the issue below. Your problem may be similar to it.
[https://github.com/wzthu/esATAC/issues/121 ](https://github.com/wzthu/esATAC/issues/121 )

**Comment by m4gold** [comment]
Works great. Thank!

**Comment by m4gold** [comment]
Worked great. Thanks!
