### ISSUE TITLE
TSS enrichment score

### ISSUE THREAD

**Issue by sk-bioinfo** [wzthu/esATAC#127]
Dear authors of esATAC,

First, thanks for the wonderful tool. 
Under the TSS enrichment module section of your sample report, I could see the 'Nuceleosome Free Reads' plot. Do you also have an option of generating TSS enrichment score, like recommended by the EnCODE project: https://www.encodeproject.org/data-standards/terms/#enrichment ?
Essentially, normalizing the above plot using the flanking regions.

Thanks
SK

**Comment by wzthu** [comment]
In current version, esATAC do not support the function you mentioned.

**Comment by sk-bioinfo** [comment]
OK. Thanks for letting me know.
