### ISSUE TITLE
Error in PeakCallingFseq

### ISSUE THREAD

**Issue by zhuangfjnu** [wzthu/esATAC#129]
start processing(paired end data): PeakCallingFseq
F-Seq Version 1.85
Error in strsplit(filename[i], split = "\\.")[[1]] : 下标出界

Any help will be appreciated

**Comment by wzthu** [comment]
Please see the issue below. Your problem may be similar to it.
[https://github.com/wzthu/esATAC/issues/121](https://github.com/wzthu/esATAC/issues/121)
