### ISSUE TITLE
Errors when run atacRepsPipe

### ISSUE THREAD

**Issue by xbjie123** [wzthu/esATAC#131]
Dear Zheng,

When I ran esATAC for the first time, I used R3.5.1 to do it. However, I could not get the report as there is an error showed that 
`pandoc version 1.12.3 or higher is required and was not found`.

So I changed to RStudio to re-do it. It's quite well that I could get all the results and reports. But the problem is that when I ran atacRepsPipe, which could combine many replicates, I got another error.
It showed that
`error reading from the connection`.

I think maybe it's caused by the large size of the files. So I changed to the R3.5.1 in our linux system. However, I get the same error
`pandoc version 1.12.3 or higher is required and was not found`.

SO, I know that I could resolve the `pandoc ` error by RStudio. But how to resolve the problem of the `connection`. Could you help me with this error? It would be very grateful for me.

Best regards,
BJ

**Comment by wzthu** [comment]
Sorry for delay. Install pandoc is difficult in China because the website are blocked. I recommend you to install Anaconda (usually for python) instead, which also contain pandoc inside.

**Comment by xbjie123** [comment]
Thanks a lot. I'm using RStudio now. It works well.
