### ISSUE TITLE
Error in dir.create

### ISSUE THREAD

**Issue by Xcubitor** [wzthu/esATAC#134]
Hello, I get the following error while running atacpipe2 after the Rgo stage:
Error in dir.create(.Object@paramlist[["scanO.dir"]]) : 'path' too long

Would anyone have any advice on that ? :-s

**Comment by wzthu** [comment]
Can you have look at this error? @Honchkrow

**Comment by Honchkrow** [comment]
The error was caused by windows/linux system, the path to the output file is too long. for example, it's about 260 characters in windows. please modify the prefix or your input file name.
