### ISSUE TITLE
Error during removeAdapter/Bowtie2Mapping

### ISSUE THREAD

**Issue by oeg5qc** [wzthu/esATAC#135]
Hello,
I've been trying to use esATAC for some ATAC-seq data I have from mice. When I run the pre-made pipeline, I encounter errors: 
"Error in file(con, "r") : cannot open the connection"
"In file(con, "r") : cannot open file 'C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipelineintermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.RemoveAdapter.report.adapter1': No such file or directory"

This also happens when I try to run the customized pipeline step-by-step by calling each function sequentially and this typically happens at the removeAdapter or Bowtie2Mapping steps. Any help would be greatly appreciated.

Full Code: 
library(dplyr)
library(esATAC)
library(magrittr)

td<-tempdir()
options(atacConf=setConfigure("tmpdir",td))
dir.create("./esATAC_pipeline")
dir.create("./esATAC_pipeline/refdir")
dir.create("./esATAC_pipeline/result")

options(atacConf=setConfigure("refdir","esATAC_pipeline/refdir"))
options(atacConf=setConfigure("tmpdir","esATAC_pipeline/result"))
options(atacConf=setConfigure("threads",2))
options(atacConf=setConfigure("genome","mm10"))

Read1 = "Td148506_USPD16089050_HNN23BBXX_L1_1.fq.gz"
Read2 = "Td148506_USPD16089050_HNN23BBXX_L1_2.fq.gz"

conclusion <- 
  atacPipe(
    # MODIFY: Change these paths to your own case files!
    # e.g. fastqInput1 = "your/own/data/path.fastq"
    fastqInput1 = Read1,
    fastqInput2 = Read2,
    # MODIFY: Change this path to an permanent path to be used in future!
    #       refdir <- "./esATAC_pipeline/refdir",
    #       tmpdir = "./esATAC_pipeline/intermediate_results", 
    # MODIFY: Set the genome for your data
    genome = "mm10")

Console:

> conclusion <- 
+   atacPipe(
+     # MODIFY: Change these paths to your own case files!
+     # e.g. fastqInput1 = "your/own/data/path.fastq"
+     fastqInput1 = Read1,
+     fastqInput2 = Read2,
+     # MODIFY: Change this path to an permanent path to be used in future!
+     #       refdir <- "./esATAC_pipeline/refdir",
+     #       tmpdir = "./esATAC_pipeline/intermediate_results", 
+     # MODIFY: Set the genome for your data
+     genome = "mm10")
2
>>>>>>========================================
Reference data configuraion start ...
Configure bsgenome ...
Configure annoDb ...
Loading required package: AnnotationDbi

Attaching package: ‘AnnotationDbi’

The following object is masked from ‘package:dplyr’:

    select

Configure knownGene ...
Loading required package: GenomicFeatures
Generate genome fasta file ...
Configure bowtie2 index ...
Configure blacklist and DHS ...
Reference data configuraion done
========================================<<<<<<
 
final esATAC_result
C:/Users/Omar/Desktop/Tomato ATAC-seq Raw Data/Td148506/esATAC_pipeline/esATAC_result
final esATAC_report
C:/Users/Omar/Desktop/Tomato ATAC-seq Raw Data/Td148506/esATAC_pipeline/esATAC_report
>>>>>>========================================
2018-11-07 20:07:11
start processing(paired end data): UnzipAndMerge
processing file:
source:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\Td148506_USPD16089050_HNN23BBXX_L1_1.fq.gz
destination:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.UnzipAndMerge.fq
processing file:
source:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\Td148506_USPD16089050_HNN23BBXX_L1_2.fq.gz
destination:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_2.UnzipAndMerge.fq
2018-11-07 21:29:43
processing finished
========================================<<<<<<
 
>>>>>>========================================
2018-11-07 21:29:45
start processing(paired end data): FastQC
processing file:
source:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.UnzipAndMerge.fqsource:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_2.UnzipAndMerge.fq
destination:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.UnzipAndMerge_FastQC.pdf
creating QC plots
2018-11-07 22:34:12
processing finished
========================================<<<<<<
 
>>>>>>========================================
2018-11-07 22:34:13
start processing(paired end data): Renamer
processing file:
source:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.UnzipAndMerge.fq
destination:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.Renamer.fq
processing file:
source:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_2.UnzipAndMerge.fq
destination:C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_2.Renamer.fq
2018-11-08 01:55:09
processing finished
========================================<<<<<<
 
>>>>>>========================================
2018-11-08 01:55:17
start processing(paired end data): RemoveAdapter
begin to find adapter
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In atacPipe(fastqInput1 = Read1, fastqInput2 = Read2, genome = "mm10") :
  path 'esATAC_pipeline/intermediate_results' is exist
2: In dir.create(esATAC_result) :
  'C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\esATAC_result' already exists
3: In dir.create(esATAC_report) :
  'C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\esATAC_report' already exists
4: In system(call, intern = TRUE, show.output.on.console = TRUE) :
  running command '"C:/Users/Omar/Documents/R/win-library/3.5/Rbowtie2/AdapterRemoval" --identify-adapters --file1 C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.Renamer.fq --file2 C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_2.Renamer.fq --threads 2 --basename C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.RemoveAdapter.report' had status 1
5: In file(con, "r") :
  cannot open file 'C:\Users\Omar\Desktop\Tomato ATAC-seq Raw Data\Td148506\esATAC_pipeline\intermediate_results/Td148506_USPD16089050_HNN23BBXX_L1_1.RemoveAdapter.report.adapter1': No such file or directory

**Comment by wzthu** [comment]
The AdapterRemoval failed to find adapter for FASTQ files so please provide adapter as parameter for the pipeline.

**Comment by wzthu** [comment]
I guess the error comes from the space in the file directory like C:\Users\Omar\Desktop\Tomato ATAC-seq Raw ， which may be recognized as 3 parameter for the command line

**Comment by oeg5qc** [comment]
I'm not sure I understand what you mean and how I should go about addressing the problem...

**Comment by wzthu** [comment]
You can put your FASTQ files or other files under a new folder with non-space directory.
For example, you can change this directory：
C:\Users\Omar\Desktop\Tomato ATAC-seq Raw
into
C:\Users\Omar\Desktop\TomatoATAC-seqRaw

**Comment by oeg5qc** [comment]
Ah I understand. I have changed the directory as you suggested and the removeAdapter function is currently running and has not finished in a few seconds with an error message which I take as a good sign. Can we keep this thread open until I am past the bowtie2 mapping step? Thanks again for your time and help.

**Comment by wzthu** [comment]
If adapter-removed FASTQ is generated successful, you can continually use this session.
You can also run R script file. The finished steps will not redo because package support breakpoint continuation.
