### ISSUE TITLE
atacRepsPipe cannot generate rep_Report

### ISSUE THREAD

**Issue by Wan-Yifei** [wzthu/esATAC#141]
Dear Zheng,

When I apply atacRepsPipe, it can generate a report for each replicate respectively. But when it tries to generate the final report rep_Report, below errors would pop up:

```
Quitting from lines 100-103 (Rep_Report.Rmd)
Error in parse(text = x, srcfile = src) : <text>:3:1: unexpected ')'
2: knitr::kable(x = getReportVal(atacProcs$DHSQC,"report")))
3: )
   ^
Calls: atacRepsPipe ... <Anonymous> -> parse_all -> parse_all.character -> parse
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Execution halted
Warning message:
system call failed: Cannot allocate memory
```

I have tried that adding `options(java.parameters = "-Xmx8192m")` at the beginning of my code. But the error still pops up. My server has 35GB memory in total. Could you please help me to figure out this problem?

**Comment by wzthu** [comment]
This is a bug. I have fixed it. Please update the package when bioconductor finish package build on sunday.

**Comment by Wan-Yifei** [comment]
Thanks for your reply. I just test the updated esATAC. It works perfectly. We enjoy it. 
I think the esATAC should be the most friendly toolbox for the general ATACseq analysis now.

Thanks for your work again. I think it's time to close this issue.
