### ISSUE TITLE
Definition of score in RPeakAnno.txt

### ISSUE THREAD

**Issue by Wan-Yifei** [wzthu/esATAC#142]
Hi wzthu,

I don't know the exact meaning of score in the RPeakAnno.txt file. esATAC calls peaks based on F-seq. But in the standard output of F-seq, the score determines the level of gray in which this feature is displayed, which should be int. But in the RPeakAnno.txt, the score is the float. So, could you please tell me the definition of score column in the RPeakAnno?

Thanks a lot!

**Comment by Honchkrow** [comment]
Hi，
    RPeakAnno.txt has a header line, I think you are talking about is PeakCallingFseq.bed.
    Can you have a look, @wzthu .

Wei Zhang

**Comment by Wan-Yifei** [comment]
> Hi，
> RPeakAnno.txt has a header line, I think what you are talking about is PeakCallingFseq.bed.
> Can you have a look, @wzthu .
> 
> Wei Zhang

Thanks for the response! Yes, the RPeakAnno has a header line as below:
```
chromatin	start	end	width	strand	name	score
chr1	3012582	3012773	192	*	chr1.1	0.023001373
```
But it doesn't explain that what's the definition of the `score`. I found that the score is extracted from the 5th columns of the PeakCallingFseq.bed.  
I just looked into the code of F-seq. I think the score should be the density of the peak. But on the website http://fureylab.web.unc.edu/software/fseq/, the score is defined as the level of gray. so, I am confused now. I want to ensure in esATAC the score is level of gray or density?

Thanks a lot!

**Comment by wzthu** [comment]
I have double checked the code of F-seq. The score is level of density.

**Comment by Wan-Yifei** [comment]
> I have double checked the code of F-seq. The score is level of density.

Got it! Thanks for your help! The website misleads me. It shows the standard format of bed file rather than the format of the output file from F-seq. 

Thank you again.
