### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by Dingersrun** [wzthu/esATAC#146]
After I installed your package, I was returned with the following comment
Error: package or namespace load failed for ‘esATAC’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
不存在叫‘TxDb.Hsapiens.UCSC.hg19.knownGene’这个名字的程辑包

**Comment by wzthu** [comment]
Please call 
```
install.packages("TxDb.Hsapiens.UCSC.hg19.knownGene")
```
to fix this problem
