### ISSUE TITLE
Error in `[<-.data.frame`(`*tmp*`, tssIndex, "Promoter", value = TRUE) :    replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by madaojjc** [wzthu/esATAC#148]
Hello, I met this problem when using atacRepsPipe2... 

2019-04-25 17:32:23
start processing(paired end data): FRiPQC
load reads
load peak
get overlap number
finish overlap
2019-04-25 17:32:25
processing finished
========================================<<<<<<
 
>>>>>>========================================
2019-04-25 17:32:25
start processing(paired end data): RPeakAnno
processing file:
source:/media/shen/disk2/jjc/2019-4-24-atac-seq/esatac_female/case/replicate1/wy-0331-5.R1_val_1.PeakCallingFseq.bed
dataframe destination:/media/shen/disk2/jjc/2019-4-24-atac-seq/esatac_female/case/replicate1/wy-0331-5.R1_val_1.RPeakAnno.txt
Image destination:/media/shen/disk2/jjc/2019-4-24-atac-seq/esatac_female/case/replicate1/wy-0331-5.R1_val_1.RPeakAnno.pdf
>> preparing features information...		 2019-04-25 17时32分26秒 
>> identifying nearest features...		 2019-04-25 17时32分26秒 
>> calculating distance from peak to TSS...	 2019-04-25 17时32分28秒 
>> assigning genomic annotation...		 2019-04-25 17时32分28秒 
Error in `[<-.data.frame`(`*tmp*`, tssIndex, "Promoter", value = TRUE) : 
  replacement has 1 row, data has 0
此外: There were 19 warnings (use warnings() to see them)

I have googled this problem but I still don't know how to solve it ....  THANKS A LOT!

**Comment by Honchkrow** [comment]
Hi madaojjc, 
    Can you provide me with your peak file? I did not see this problem before.
    My e-mail address: w-zhang16@mails.tsinghua.edu.cn
Wei

**Comment by madaojjc** [comment]
> Hi madaojjc,
> Can you provide me with your peak file? I did not see this problem before.
> My e-mail address: [w-zhang16@mails.tsinghua.edu.cn](mailto:w-zhang16@mails.tsinghua.edu.cn)
> Wei

Sorry for replying you so late, I wanted to rerun the esATAC and send the peak file to you, but when I rerun the pipeline, I met another error, by the way, my R version is 3.6.0


2019-05-06 16:40:43
start processing(paired end data): RPeakAnno
processing file:
source:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.PeakCallingFseq.bed
dataframe destination:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.RPeakAnno.txt
Image destination:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.RPeakAnno.pdf
>> preparing features information...		 2019-05-06 16时40分44秒 
>> identifying nearest features...		 2019-05-06 16时40分45秒 
>> calculating distance from peak to TSS...	 2019-05-06 16时40分45秒 
>> assigning genomic annotation...		 2019-05-06 16时40分45秒 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NSBS’ for signature ‘"SortedByQueryHits"’
此外: There were 17 warnings (use warnings() to see them)

**Comment by madaojjc** [comment]
Sorry for replying you so late, I wanted to rerun the esATAC and send the peak file to you, but when I rerun the pipeline, I met another error, by the way, my R version is 3.6.0




Sorry for replying you so late, I wanted to rerun the esATAC and send the peak file to you, but when I rerun the pipeline, I met another error, by the way, my R version is 3.6.0

2019-05-06 16:40:43
start processing(paired end data): RPeakAnno
processing file:
source:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.PeakCallingFseq.bed
dataframe destination:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.RPeakAnno.txt
Image destination:/media/shen/disk2/jjc/2019-4-24-atac-seq-mouse/esatac_female/case/replicate1/wy-0331-5.R1.RPeakAnno.pdf

preparing features information... 2019-05-06 16时40分44秒
identifying nearest features... 2019-05-06 16时40分45秒
calculating distance from peak to TSS... 2019-05-06 16时40分45秒
assigning genomic annotation... 2019-05-06 16时40分45秒
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘NSBS’ for signature ‘"SortedByQueryHits"’
此外: There were 17 warnings (use warnings() to see them)







At 2019-05-04 16:43:34, "Honchkrow" <notifications@github.com> wrote:


Hi madaojjc,
Can you provide me with your peak file? I did not see this problem before.
My e-mail address: w-zhang16@mails.tsinghua.edu.cn
Wei

**Comment by Honchkrow** [comment]
Hi madaojjc,
    I ran the pipeline using R 3.6.0, but cannot reproduce your problem. 
    Can you send me with your run script and peak file (only the peak file is ok), I'd like to help you tackle this question.
Wei
