### ISSUE TITLE
major problem in atacpipe2 / java

### ISSUE THREAD

**Issue by Xcubitor** [wzthu/esATAC#153]
When I run atacpipe2 I get:
start processing(paired end data): PeakCallingFseq
F-Seq Version 1.85
Error in strsplit(filename[i], split = "\\.")[[1]] : 
  subscript out of bounds

or

start processing(paired end data): PeakCallingFseq
Error in .jcall("edu/duke/igsp/gkde/Main", "V", "main", argvs) : 
  java.lang.OutOfMemoryError: Requested array size exceeds VM limit

I have 64GB RAM and I increased the java limits using -Xmx60192m and XX:MaxMetaspaceSize=60192m   but still no solution. Heeeeeelp :-(

**Comment by wzthu** [comment]
Did you increase memory limitation before `library(esATAC)` ?

**Comment by Xcubitor** [comment]
Hey, thanks for responding. I did all this before but it did not resolve this issue :-(

**Comment by lwx19911226** [comment]
I think the error "Error in strsplit(filename[i], split = "\.")[[1]] : subscript out of bounds" comes from "filename<-list.files(.Object@paramlist[["outTmpDir"]])
        for(i in 1:length(filename)){
            filename[i]<-strsplit(filename[i],split="\\.")[[1]][1]
        }" in PeakCallingFseq.R. When length(filename) is 0, i will loop in c(1,0).

**Comment by wzthu** [comment]
Usually, due to the java memory limitation or data quality, F-seq fails to call peak and generate peak BED file. This error will occur because the downstream program can not find BED file.

**Comment by Andaukmoan** [comment]
I am having this same issue and have tried increasing the memory limitation (I have 64GB of RAM as well). I have kept the files from the initial run so that I do not have to wait 10 hours to get back to step 13. Do I need to let the program run from the beginning with the increased memory limitation for it to work?
