### ISSUE TITLE
Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘NSBS’ for signature ‘"SortedByQueryHits"’

### ISSUE THREAD

**Issue by anai1031** [wzthu/esATAC#154]
Hi, there,

I tried to feed in the bed file of my peaks into the function "peakanno", but I got the similar error as in one previous post:
2019-10-13 16:50:05
start processing(paired end data): RPeakAnno
processing file:
source:/BGFS1/home/wuq/data/test/KO-Treg.bed
dataframe destination:/BGFS1/home/wuq/data/test/KO-Treg.RPeakAnno.txt
Image destination:/BGFS1/home/wuq/data/test/KO-Treg.RPeakAnno.pdf
>> preparing features information...		 2019-10-13 04:50:05 PM 
>> identifying nearest features...		 2019-10-13 04:50:05 PM 
>> calculating distance from peak to TSS...	 2019-10-13 04:50:05 PM 
>> assigning genomic annotation...		 2019-10-13 04:50:05 PM 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NSBS’ for signature ‘"SortedByQueryHits"’
In addition: Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
3: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
4: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
5: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

My code is as follows: 
batch1 <- "/path to/KO-Treg.bed.bz2"
peak1_path <- as.vector(bunzip2(filename = batch1, destname = file.path(getwd(), "KO-Treg.bed"), ext="bz2", FUN=bzfile, overwrite=TRUE, remove = FALSE))
AnnoInfo <- peakanno(peakInput = peak1_path, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, annoDb = "org.Mm.eg.db")

Could you please help me to have a look?

Thanks so much!

Best wishes,
Qiong

**Comment by Honchkrow** [comment]
Hello, 

    This question may caused by string "chr", see [here](https://support.bioconductor.org/p/124664/), please check your bed file and try again.

Wei

**Comment by anai1031** [comment]
Thank U, Wei! This really works!!
