### ISSUE TITLE
Handling large fastq files

### ISSUE THREAD

**Issue by tghosh30** [wzthu/esATAC#171]
Hi,

I'm having some issues running the pipeline.

After running these commands, R session gets aborted. I can see that the package also depends ShortRead (which uses the FastqStreamer function). Are there any hacks to deal with large fastq files (ranging from 3-12 GB)? 
######
library(esATAC)
# call pipeline
conclusion <- 
    atacPipe(
        # MODIFY: Change these paths to your own case files!
        # e.g. fastqInput1 = "your/own/data/path.fastq"
        fastqInput1 ="ATCT_Seq_2_S53_L003_R1_001.fastq.gz",
        fastqInput2 = "ATCT_Seq_2_S53_L003_R2_001.fastq.gz", 
        # Reference genome:
        genome = "hg19")
#######

Thanks.

**Comment by Honchkrow** [comment]
Hi，

When using esATAC, there should be some report. Can you provide us with the report information, therefore we can see which step caused the interrupt.

We have tested larger fastq.gz files, I guess that this problem was caused by out of memory. How much RAM do you have in your pc?

Wei

**Comment by tghosh30** [comment]
Thanks for your quick response. 

Reproducible example:
library(esATAC)
conclusion <-
atacPipe(
# MODIFY: Change these paths to your own case files!
# e.g. fastqInput1 = "your/own/data/path.fastq"
fastqInput1 ="ATCT_Seq_2_S53_L003_R1_001.fastq.gz",
fastqInput2 = "ATCT_Seq_2_S53_L003_R2_001.fastq.gz",
# Reference genome:
genome = "hg19")
Console:
Configure bsgenome ...
Configure bsgenome finished
Configure knownGene ...
Configure knownGene finished
Configure annoDb ...
Configure annoDb finished
Configure fasta ...
Configure fasta finished
Configure bt2Idx ...
--threads 2
arguments 'show.output.on.console', 'minimized' and 'invisible' are for Windows only
#######

R session was getting aborted after this step after ~30 minutes. I was using 8GB RAM.

Thanks.

**Comment by Honchkrow** [comment]
hi,
    CAN you try the code with more memory, the boetiw2 index is not building. 8g seems too small.

**Comment by wzthu** [comment]
The output shows that it stops at building bowtie2 index. I test the program that bowtie2 requires about 7GB memory. 8 GB memory may not be enough for both OS and esATAC.  We recommend using a PC with at least 16GB.
Alternative, you can download the reference and set the  directory of `refdir` to skip those steps:
[https://cloud.tsinghua.edu.cn/d/9690881ae9134ba39fd4/](https://cloud.tsinghua.edu.cn/d/9690881ae9134ba39fd4/)
But it does not ensure the later steps will work.
